// Generated by https://quicktype.io

export interface MyBooking {
    bookingId: number;
    status:    boolean;
    checkIn:   string;
    checkOut:  string;
    rooms:     number;
    roomName:  string;
    email : string
}
